KB-PJT-15-4/BE

src/main/java/org/moa/trip/controller/TripController.java
src/main/java/org/moa/trip/dto/expense/ExpenseCreateRequestDto.java
src/main/java/org/moa/trip/dto/expense/ExpenseResponseDto.java
src/main/java/org/moa/trip/entity/SettlementNotes.java
src/main/java/org/moa/trip/mapper/ExpenseMapper.java
src/main/java/org/moa/trip/mapper/SettlementMapper.java
src/main/java/org/moa/trip/service/ExpenseService.java
src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
src/main/java/org/moa/trip/service/SettlementService.java
src/main/java/org/moa/trip/service/SettlementServiceImpl.java
src/main/java/org/moa/trip/service/TripService.java
src/main/java/org/moa/trip/service/TripServiceImpl.java
src/main/resources/org/moa/trip/mapper/ExpenseMapper.xml
src/main/resources/org/moa/trip/mapper/SettlementMApper.xml
src/test/java/org/moa/trip/service/ExpenseServiceImplTest.java
src/test/java/org/moa/trip/service/SettlementServiceImplTest.java

Feat : 정산 조회하기 기능 구현

---

src/main/java/org/moa/global/account/mapper/AccountMapper.java
src/main/java/org/moa/global/security/controller/SecurityController.java
src/main/java/org/moa/member/controller/MemberController.java
src/main/java/org/moa/member/dto/verify/MemberVerifyRequestDto.java
src/main/java/org/moa/member/service/MemberService.java
src/main/java/org/moa/member/service/MemberServiceImpl.java
src/main/resources/org/moa/global/account/mapper/AccountMapper.xml

- 회원가입 전 인증정보(이름, 주민등록번호, 계좌, 계좌비밀번호)가 유효한지 확인
- 회원가입 진행
- 관련된 이슈 번호를 적어주세요 (#2 )

feat: 회원가입 인증 및 회원가입 수정

---

src/main/java/org/moa/global/account/controller/AccountController.java
src/main/java/org/moa/global/account/dto/payment/PaymentRequestDto.java
src/main/java/org/moa/global/account/dto/payment/PaymentResponseDto.java
src/main/java/org/moa/global/account/entity/PaymentRecord.java
src/main/java/org/moa/global/account/mapper/AccountMapper.java
src/main/java/org/moa/global/account/mapper/PaymentRecordMapper.java
src/main/java/org/moa/global/account/service/AccountService.java
src/main/java/org/moa/global/account/service/AccountServiceImpl.java
src/main/java/org/moa/global/type/StatusCode.java
src/main/resources/org/moa/global/account/mapper/AccountMapper.xml
src/main/resources/org/moa/global/account/mapper/PaymentRecordMapper.xml

- 결제 기능 추가
-  (#2)
```
{
"price" : 3000,
"paymentName": "윈터가 좋아하는 아이스크림"
}
```
price (금액) , paymentName (결제 이름) => CustomUser 클래스의 객체에서 memberId를 추출해서 사용

feat: 결제 기능 추가

---

src/main/java/org/moa/global/config/RootConfig.java
src/main/java/org/moa/global/config/ServletConfig.java
src/main/java/org/moa/global/type/ResKind.java
src/main/java/org/moa/reservation/transport/controller/TransportController.java
src/main/java/org/moa/reservation/transport/dto/TransportInfoResponse.java
src/main/java/org/moa/reservation/transport/mapper/TransportMapper.java
src/main/java/org/moa/reservation/transport/service/TransportService.java
src/main/java/org/moa/reservation/transport/service/TransportServiceImpl.java
src/main/java/org/moa/reservation/transport/type/Status.java
src/main/resources/org/moa/reservatioin/transport/mapper/TransportMapper.xml

- 출발지, 도착지, 출발시각에 따른 교통편을 조회하는 기능 추가
-  (#21 )

feat: 교통편 조회 기능 추가

---

src/main/java/org/moa/global/account/controller/AccountController.java
src/main/java/org/moa/reservation/mapper/ReservationMapper.java
src/main/java/org/moa/reservation/transport/controller/TransportController.java
src/main/java/org/moa/reservation/transport/dto/TransPaymentRequestDto.java
src/main/java/org/moa/reservation/transport/mapper/TransportMapper.java
src/main/java/org/moa/reservation/transport/service/TransportService.java
src/main/java/org/moa/reservation/transport/service/TransportServiceImpl.java
src/main/resources/org/moa/reservation/mapper/ReservationMapper.xml
src/main/resources/org/moa/reservation/transport/mapper/TransportMapper.xml

- 교통 예약을 확정하기 위한 결제 기능을 추가하였습니다.
- 관련된 이슈 번호를 적어주세요 (#21 )

Feat: 교통 좌석 예약 확정(결제) 기능

---

src/main/java/org/moa/reservation/accommodation/controller/AccommodationController.java
src/main/java/org/moa/reservation/accommodation/dto/AccommodationReservationRequestDto.java
src/main/java/org/moa/reservation/accommodation/service/AccommodationService.java
src/main/java/org/moa/reservation/accommodation/service/AccommodationServiceImpl.java
src/main/java/org/moa/trip/controller/TripController.java
src/main/java/org/moa/trip/dto/expense/ExpenseResponseDto.java
src/main/java/org/moa/trip/dto/settlement/SettlementProgressResponseDto.java
src/main/java/org/moa/trip/service/ExpenseService.java
src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
src/main/java/org/moa/trip/service/TripServiceImpl.java
src/test/java/org/moa/trip/service/ExpenseServiceImplTest.java
src/test/java/org/moa/trip/service/TripServiceImplTest.java

- /expense , /settlement-progress API expenseDate Null 문제 수정
- 

Fix : expenseDate Null 문제 해결

---

src/main/java/org/moa/reservation/accommodation/mapper/AccomResMapper.java
src/main/java/org/moa/reservation/accommodation/service/AccommodationServiceImpl.java
src/main/java/org/moa/trip/controller/TripController.java
src/main/java/org/moa/trip/dto/settlement/SettlementRequestDto.java
src/main/java/org/moa/trip/mapper/SettlementMapper.java
src/main/java/org/moa/trip/service/ExpenseService.java
src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
src/main/java/org/moa/trip/service/SettlementServiceImpl.java
src/main/resources/org/moa/reservation/accommodation/mapper/AccomResMapper.xml
src/main/resources/org/moa/trip/mapper/SettlementMApper.xml
src/test/java/org/moa/trip/service/ExpenseServiceImplTest.java

- getExpenses memberId 제거, 페이징 적용했습니다
- #4
- 예약은 아직 구현중입니다

Fix : getExpenses memberId 제거, 페이징 적용

---

src/main/java/org/moa/reservation/mapper/ReservationMapper.java
src/main/java/org/moa/reservation/transport/controller/TransportController.java
src/main/java/org/moa/reservation/transport/dto/TransResCancelRequestDto.java
src/main/java/org/moa/reservation/transport/dto/TransResRequestDto.java
src/main/java/org/moa/reservation/transport/dto/TransResStatusDto.java
src/main/java/org/moa/reservation/transport/dto/TransSeatsInfoResponse.java
src/main/java/org/moa/reservation/transport/dto/TranstInfoResponse.java
src/main/java/org/moa/reservation/transport/mapper/TransportMapper.java
src/main/java/org/moa/reservation/transport/service/TransportService.java
src/main/java/org/moa/reservation/transport/service/TransportServiceImpl.java
src/main/resources/org/moa/reservation/mapper/ReservationMapper.xml
src/main/resources/org/moa/reservation/transport/mapper/TransportMapper.xml

- 교통 예약과정 중 결제 직전 취소 기능 추가
- (#21 )

feat: 교통 좌석 결제전 취소 기능

---

src/main/java/org/moa/global/config/RootConfig.java
src/main/java/org/moa/global/config/ServletConfig.java
src/main/java/org/moa/reservation/restaurant/controller/CategoryController.java
src/main/java/org/moa/reservation/restaurant/dto/CategoryResponseDto.java
src/main/java/org/moa/reservation/restaurant/service/CategoryServiceImpl.java

- 식당 카테고리 조회 API의 응답 형식 수정
- (#30 )
- Controller에서 직접 리스트를 반환하던 방식을 ApiResponse.of()로 수정

fix: 식당 카테고리 조회 API

---

src/main/java/org/moa/global/account/service/AccountServiceImpl.java
src/main/java/org/moa/global/type/ResKind.java
src/main/java/org/moa/reservation/accommodation/controller/AccommodationController.java
src/main/java/org/moa/reservation/accommodation/entity/AccommodationInfo.java
src/main/java/org/moa/reservation/accommodation/mapper/AccomResMapper.java
src/main/java/org/moa/reservation/accommodation/service/AccommodationService.java
src/main/java/org/moa/reservation/accommodation/service/AccommodationServiceImpl.java
src/main/resources/org/moa/reservation/accommodation/mapper/AccomResMapper.xml
src/main/resources/org/moa/reservation/accommodation/mapper/AccommodationMapper.xml

- ResKind에 ACCOMODATION -> ACCOMMODATION 오타 수정했습니다
- 숙소 예약 기능 구현했습니다
- #33 

Feat : 숙소 예약 구현

---

src/main/java/org/moa/trip/controller/TripController.java
src/main/java/org/moa/trip/mapper/TripMapper.java
src/main/java/org/moa/trip/service/TripService.java
src/main/java/org/moa/trip/service/TripServiceImpl.java
src/main/resources/org/moa/trip/mapper/TripMapper.xml

- locationName 파라미터를 추가하여 지역별 필터링이 가능하게 수정
- #49 

feat:  여행 목록 조회 locationName 파라미터 추가

---

src/main/java/org/moa/reservation/restaurant/controller/RestaurantController.java
src/main/java/org/moa/reservation/restaurant/dto/RestaurantInfoResponseDto.java
src/main/java/org/moa/reservation/restaurant/mapper/RestaurantMapper.java
src/main/java/org/moa/reservation/restaurant/service/RestaurantService.java
src/main/java/org/moa/reservation/restaurant/service/RestaurantServiceImpl.java
src/main/resources/org/moa/reservation/restaurant/mapper/RestaurantMapper.xml

- /api/member/reservation/restaurant/restId 로 식당 정보를 조회합니다.
- (#30 )

feat: 식당 정보 조회 API 구현

---

src/main/java/org/moa/reservation/dto/ReservationItemResponseDto.java
src/main/resources/org/moa/reservation/accommodation/mapper/AccommodationMapper.xml
src/main/resources/org/moa/reservation/restaurant/mapper/RestaurantMapper.xml
src/main/resources/org/moa/reservation/transport/mapper/TransportMapper.xml

fix: 예약내역 반환값에 예약ID 포함

---

sql_test/database.sql

- 사업자용 테스트 케이스 추가
- DDL, DML 코드 수정
- 관련된 이슈 번호를 적어주세요 (#2 )
- 

refactor: 사업자 계정 테스트 케이스 추가

---

src/main/java/org/moa/member/controller/MemberController.java
src/main/java/org/moa/member/service/MemberService.java
src/main/java/org/moa/member/service/MemberServiceImpl.java
src/main/java/org/moa/trip/dto/trip/AddMemberRequestDto.java
src/main/java/org/moa/trip/mapper/TripMemberMapper.java
src/main/java/org/moa/trip/service/ExpenseServiceImpl.java
src/main/java/org/moa/trip/service/TripServiceImpl.java
src/main/resources/org/moa/trip/mapper/TripMemberMapper.xml

- memberController의 search-by-email 라우팅 리팩터링, 해당 멤버가 여행에 이미 존재하면 BAD_REQUEST, 아니라면 memberId 리턴합니다.
- 여행에 사용자 초대시 memberIds : [2 , 3] 처럼 리스트 형태로 여러명을 초대 가능합니다

Fix : 여행에 사용자 여러명 추가 기능, 해당 멤버가 여행에 있는지 검사 기능 추가

---

sql_test/database.sql
sql_test/insert_tran_res_aug1_to_aug7_ver2.sql

- 08.11 수정본
- 관련된 이슈 번호를 적어주세요 (#issue_number)

08.11 sql 수정

---

sql_test/database.sql
src/main/java/org/moa/global/util/QrCodeUtil.java

- QrCodeUtil 테스트문 삭제했습니다.
- (#2 )

fix: QrCodeUtil 테스트문 삭제

---

src/main/java/org/moa/reservation/restaurant/mapper/RestaurantMapper.java
src/main/java/org/moa/trip/service/TripServiceImpl.java
src/main/resources/org/moa/reservation/restaurant/mapper/RestaurantMapper.xml

- 여행 생성 동시에 여행 날짜별 식당 예약칸이 생성됩니다.
- (#30 )

fix: 식당 예약칸 자동 생성

---

src/main/resources/org/moa/reservation/accommodation/mapper/AccommodationMapper.xml

- 예약 Mapper 로직 수정했습니다.
- 관련된 이슈 번호를 적어주세요 (#issue_number)

Fix : 예약 로직 수정

---

sql_test/database.sql

- 어떤 변경사항이 있는지 설명해주세요.
- 관련된 이슈 번호를 적어주세요 (#issue_number)

chore: 교통정보 테이블 business_id컬럼 추가
